routes/web.php
<?php

use App\Http\Controllers\Admin\CompanyController;
use App\Http\Controllers\Admin\CustomerController;
use App\Http\Controllers\Admin\DashboardController;
use App\Http\Controllers\Auth\AuthController;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


Route::match(['post','get'],'/login',[AuthController::class,'index'])->name('admin.login');
Route::match(['post','get'],'/',[AuthController::class,'create'])->name('admin.create');

    Route::prefix('admin')->group(function (){
        Route::get('/dashboard',[DashboardController::class,'index'])->name('admin.dashboard');
        Route::resource('/company',CompanyController::class);
        Route::resource('/customer',CustomerController::class);

    });

app/Models/Company.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Company extends Model
{
    use HasFactory;
    protected $guarded;

    public function getCustomer()
    {
        return $this->hasOne(Customer::class,'id','customer_id')->withDefault();
    }
}

app/Http/Controllers/Admin/CompanyController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use App\Models\Company;
use App\Models\Customer;
use Illuminate\Http\Request;
use Illuminate\Support\Str;

class CompanyController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $companies = Company::all();
        return view('admin.company.index',compact('companies'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $customers =Customer::all();
        return  view('admin.company.create',compact('customers'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $company = Company::create([
            'company_name'=>$request->company_name,
            'name_surname'=>$request->name.''.$request->surname,
            'email'=>$request->email,
            'password'=>$request->password,
            'website'=>$request->website,
            'text'=>$request->contents,
            'customer_id'=>$request->customer,
            'company_code'=>Str::random(12),
        ]);
        return redirect()->route('company.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $company=Company::findOrFail($id);
        $customers=Customer::all();
        return  view('admin.company.update',compact('company','customers'));

    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $company=Company::findOrFail($id);
        $company->company_name =$request->company_name;
        $company->name_surname =$request->name;
        $company->email =$request->email;
        $company->website =$request->website;
        $company->customer_id =$request->customer;
        $company->save();
        return  redirect()->route('company.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $company = Company::findOrFail($id);
        $company->delete();
        return redirect()->route('company.index');
    }
}

resources/views/admin/company/create.blade.php
@extends('admin.layouts.master')
@section('title','Şirket Olustur')
@section('content')


    <div class="card shadow mb-4">
        <div class="card-header py-3">
            <h6 class="m-0 font-weight-bold text-primary">Yeni Şirket Kaydı</h6>
        </div>
        <div class="card-body">
            @if($errors->any())
                <div class="alert alert-danger">
                    @foreach($errors->all() as $error)
                        <li>{{ $error }}</li>
                    @endforeach
                </div>
            @endif
            <form action="{{ route('company.store') }}" method="POST" enctype="multipart/form-data">
                @csrf
                <div class="form-group">
                    <label for="">Şirket İsmi</label>
                    <input type="text" class="form-control" name="company_name">
                </div>
                <div class="form-group">
                    <label for="">isim</label>
                    <input type="text" class="form-control" name="name">
                </div> <div class="form-group">
                    <label for="">Soyisim</label>
                    <input type="text" class="form-control" name="surname">
                </div>

                <div class="form-group">
                    <label for="">Email</label>
                    <input type="email" class="form-control" name="email">
                </div>
                <div class="form-group">
                    <label for="">Sifre</label>
                    <input type="password" class="form-control" name="password">
                </div>
                <div class="form-group">
                    <label for="">Website</label>
                    <input type="text" class="form-control" name="website">
                </div>
                <div class="form-group">
                    <label for="">Tanıtım Metni</label>
                    <textarea  id="summernote" class="form-control" rows="4" name="contents"></textarea>
                </div>

                <div class="form-group">
                    <label >Müşteri</label>
                    <select name="customer" class="form-control">
                        <option value="">Secim Yapınız</option>
                        @foreach($customers as $customer)
                            <option value="{{ $customer->id }}">{{ $customer->name_surname }}</option>
                        @endforeach
                    </select>
                </div>

                <div class="form-group">
                    <button class="form-control btn btn-outline-primary">Müşteri Olustur.</button>
                </div>
            </form>
        </div>
    </div>
@endsection
@section('css')
    <link href="https://cdn.jsdelivr.net/npm/summernote@0.8.18/dist/summernote.min.css" rel="stylesheet">
@endsection
@section('js')
    <script src="https://cdn.jsdelivr.net/npm/summernote@0.8.18/dist/summernote.min.js"></script>
    <script>
        $(document).ready(function() {
            $('#summernote').summernote({
                'height':300
            });
        });
    </script>
@endsection

resources/views/admin/company/index.blade.php
@extends('admin.layouts.master')
@section('title','Hizmet Veren Şirketler')
@section('content')

    <div class="card shadow mb-4">
        <div class="card-header py-3">
            <h6 class="m-0 font-weight-bold text-primary">Tüm Şirketler</h6>
        </div>
        <div class="card-body">
            <div class="table-responsive">
                <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
                    <thead>
                    <tr>
                        <th>ID</th>
                        <th>Logo</th>
                        <th>Firma Adı</th>
                        <th>İsim Soyisim</th>
                        <th>E-mail</th>
                        <th>WebSite</th>
                        <th>Müsteriler</th>
                        <th>Olusturma Tarihi</th>
                        <th>İşlemler</th>
                    </tr>
                    </thead>
                    <tbody>
                    @foreach($companies as $company)
                        <tr>
                            <td>{{ $company->id }}</td>
                            <td>
                                <img src="{{ $company->logo }}" alt="" width="90">
                            </td>
                            <td>{{ $company->company_name }}</td>
                            <td>{{ $company->name_surname}}</td>
                            <td>{{ $company->email }}</td>
                            <td>{{ $company->website }}</td>
                            <td>{{ $company->getCustomer->name_surname }}</td>
                           <td>{{ \Carbon\Carbon::parse($company->created_at)->format('j F, Y') }}</td>
                            <td >
                                <a href="#" class="btn btn-outline-success form-control mb-1"><i class="fa fa-eye"></i></a>
                                <a href="{{ route('company.edit',$company->id) }}"   class="btn btn-outline-secondary form-control mb-1"><i class="fa fa-edit"></i></a>
                                <form action="{{ route('company.destroy',$company->id) }}" method="POST">
                                    @csrf
                                    @method('DELETE')
                                    <button href="" class="btn btn-outline-danger form-control"><i class="fa fa-times"></i></button>

                                </form>
                            </td>
                        </tr>
                    @endforeach

                    </tbody>

                </table>

            </div>
        </div>
    </div>


@endsection

resources/views/admin/company/update.blade.php
@extends('admin.layouts.master')
@section('title','Müşteri güncelleme')
@section('content')
    <div class="card shadow mb-4">
        <div class="card-header py-3">
            <h6 class="m-0 font-weight-bold text-primary">Şirket Güncelle</h6>
        </div>
        <div class="card-body">
            @if($errors->any())
                <div class="alert alert-danger">
                    @foreach($errors->all() as $error)
                        <li>{{ $error }}</li>
                    @endforeach
                </div>
            @endif
            <form action="{{ route('company.update',$company->id) }}" method="POST" enctype="multipart/form-data" >
                @method('PUT')
                @csrf
                <div class="form-group">
                    <label for="">Şirket İsmi</label>
                    <input type="text" class="form-control" name="company_name" value="{{ $company->company_name }}">
                </div>
                <div class="form-group">
                    <label for="">İsim Soyisim</label>
                    <input type="text" class="form-control" name="name" value="{{ $company->name_surname }}">
                </div>
                <div class="form-group">
                    <label for="">Email</label>
                    <input type="text" class="form-control" name="email" value="{{ $company->email }}">
                </div>
                <div class="form-group">
                    <label for="">WebSite</label>
                    <input type="text" class="form-control" name="website" value="{{ $company->website }}">
                </div>

                <div class="form-group">
                    <label >Müşteri</label>
                    <select name="customer" class="form-control">
                        <option value="">Secim Yapınız</option>
                        @foreach($customers as $customer)
                            <option value="{{ $customer->id }}">{{ $customer->name_surname }}</option>
                        @endforeach
                    </select>
                </div>
                <div class="form-group">
                    <button class="form-control btn btn-outline-primary">Bilgileri Güncelle</button>
                </div>
            </form>
        </div>
    </div>



@endsection