routes/web.php
<?php

use App\Http\Controllers\Admin\CompanyController;
use App\Http\Controllers\Admin\CustomerController;
use App\Http\Controllers\Admin\DashboardController;
use App\Http\Controllers\Auth\AuthController;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


Route::match(['post','get'],'/login',[AuthController::class,'index'])->name('admin.login');
Route::match(['post','get'],'/',[AuthController::class,'create'])->name('admin.create');

    Route::prefix('admin')->group(function (){
        Route::get('/dashboard',[DashboardController::class,'index'])->name('admin.dashboard');
        Route::resource('/company',CompanyController::class);
        Route::resource('/customer',CustomerController::class);

    });

app/Models/Customer.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Customer extends Model
{
    use HasFactory;
    protected $guarded;
    public function getCompany()
    {
        return $this->hasOne(Company::class,'id','company_id')->withDefault();
    }
}

app/Http/Controllers/Admin/CustomerController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use App\Models\Company;
use App\Models\Customer;
use Illuminate\Database\Eloquent\Relations\HasOne;
use Illuminate\Http\Request;

class CustomerController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
         $customers = Customer::all();
         return  view('admin.customer.index',compact('customers'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $copmanies = Company::all();
        return view('admin.customer.create',compact('copmanies'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)

    {
        $request->validate([
            'name' => 'required|min:2|max:25',
            'surname' => 'required|min:2|max:25',
            'email' => 'required|email',

        ]);

        $customer = Customer::create([
            'name_surname'=>$request->name.''.$request->surname,
            'email'=>$request->email,
            'password'=>$request->password,
            'company_id'=>$request->customer
        ]);
        return redirect()->route('customer.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $customer=Customer::findOrFail($id);
        $company =Company::all();
        return  view('admin.customer.update',compact('customer','company'));



    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {

        $customer = Customer::findOrFail($id);
        $customer->name_surname=$request->name;
        $customer->email=$request->email;
        $customer->company_id=$request->customer;
        $customer->save();


        return redirect()->route('customer.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $customers = Customer::findOrFail($id);
        $customers->delete();
        return redirect()->route('customer.index');
    }
}

resources/views/admin/customer/create.blade.php
@extends('admin.layouts.master')
@section('title','Müsteri Olustur')
@section('content')


    <div class="card shadow mb-4">
        <div class="card-header py-3">
            <h6 class="m-0 font-weight-bold text-primary">Yeni Müşteri Kaydı</h6>
        </div>
        <div class="card-body">
            @if($errors->any())
                <div class="alert alert-danger">
                    @foreach($errors->all() as $error)
                        <li>{{ $error }}</li>
                    @endforeach
                </div>
            @endif
            <form action="{{ route('customer.store') }}" method="POST" enctype="multipart/form-data">
            @csrf
            <div class="form-group">
                <label for="">İsim</label>
                <input type="text" class="form-control" name="name">
            </div>
                <div class="form-group">
                    <label for="">Soyisim</label>
                    <input type="text" class="form-control" name="surname">
                </div>

            <div class="form-group">
                <label for="">Email</label>
                <input type="email" class="form-control" name="email">
            </div>
                <div class="form-group">
                    <label for="">Şifre</label>
                    <input type="password" class="form-control" name="password">
                </div>

                <div class="form-group">
                    <label >Müşteri</label>
                    <select name="customer" class="form-control">
                        <option value="">Secim Yapınız</option>
                        @foreach($copmanies as $copmany)
                            <option value="{{ $copmany->id }}">{{ $copmany->company_name }}</option>
                        @endforeach
                    </select>
                </div>
            <div class="form-group">
                <button class="form-control btn btn-outline-primary">Müşteri Olustur.</button>
            </div>
            </form>
        </div>
    </div>



@endsection

resources/views/admin/customer/index.blade.php
@extends('admin.layouts.master')
@section('title','Müşteriler')
@section('content')
    <div class="card shadow mb-4">
        <div class="card-header py-3">
            <h6 class="m-0 font-weight-bold text-primary">Tüm Müşteriler</h6>
        </div>
        <div class="card-body">
            <div class="table-responsive">
                <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
                    <thead>
                    <tr>
                        <th>ID</th>
                        <th>İsim Soyisim</th>
                        <th>E-mail</th>
                        <th>Şirketler</th>
                        <th>Olusturma Tarihi</th>
                        <th>İşlemler</th>
                    </tr>
                    </thead>
                    <tbody>
                    @foreach($customers as $customer)
                        <tr>
                            <td>{{ $customer->id }}</td>
                            <td>{{ $customer->name_surname	 }}</td>
                            <td>{{ $customer->email	 }}</td>
                            <td>{{ ($customer->getCompany->company_name)}}</td>
                            <td>{{ \Carbon\Carbon::parse($customer->created_at)->format('j F, Y') }}</td>
                            <td >
                                <a href="#" class="btn btn-outline-success form-control mb-1"><i class="fa fa-eye"></i></a>
                                <a href="{{ route('customer.edit',$customer->id) }}"   class="btn btn-outline-secondary form-control mb-1"><i class="fa fa-edit"></i></a>
                                <form action="{{ route('customer.destroy',$customer->id) }}" method="POST">
                                    @csrf
                                    @method('DELETE')
                                    <button href="" class="btn btn-outline-danger form-control"><i class="fa fa-times"></i></button>

                                </form>
                            </td>
                        </tr>
                    @endforeach

                    </tbody>

                </table>

            </div>
        </div>
    </div>

@endsection

resources/views/admin/customer/update.blade.php
@extends('admin.layouts.master')
@section('title','Müşteri güncelleme')
@section('content')
    <div class="card shadow mb-4">
        <div class="card-header py-3">
            <h6 class="m-0 font-weight-bold text-primary">Tüm Yazılar</h6>
        </div>
        <div class="card-body">
            @if($errors->any())
                <div class="alert alert-danger">
                    @foreach($errors->all() as $error)
                        <li>{{ $error }}</li>
                    @endforeach
                </div>
            @endif
            <form action="{{ route('customer.update',$customer->id) }}" method="POST" enctype="multipart/form-data" >
                @method('PUT')
                @csrf
                <div class="form-group">
                    <label for="">İsim Soyisim</label>
                    <input type="text" class="form-control" name="name" value="{{ $customer->name_surname }}">
                </div>
                <div class="form-group">
                    <label for="">Email</label>
                    <input type="text" class="form-control" name="email" value="{{ $customer->email }}">
                </div>
                <div class="form-group">
                    <label >Müşteri</label>
                    <select name="customer" class="form-control">
                        <option value="">Secim Yapınız</option>
                        @foreach($company as $compan)
                            <option value="{{ $compan->id }}">{{ $compan->company_name }}</option>
                        @endforeach
                    </select>
                </div>


    </div>
                </div>

                <div class="form-group">
                    <button class="form-control btn btn-outline-primary">Bilgileri Güncelle</button>
                </div>
            </form>
        </div>
    </div>



@endsection